version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run dev
