services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      PYTHONUNBUFFERED: "1"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  script-generator:
    build:
      context: .
      dockerfile: scripts-generator/Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  video-creator:
    build:
      context: .
      dockerfile: video-creator/Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - videos-data:/app/data/videos
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: api/Dockerfile    ports:
      - "8080:8080"
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      REDIS_URL: "redis://redis:6379/0"
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - videos-data:/app/data/videos
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5000:80"
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:8080
    depends_on:
      - api
    restart: unless-stopped

volumes:
  videos-data:
    driver: local
