version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      PYTHONUNBUFFERED: "1"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  script-generator:
    build:
      context: .
      dockerfile: scripts-generator/Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  video-creator:
    build:
      context: .
      dockerfile: video-creator/Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - videos-data:/app/data/videos
    restart: on-failure

  publisher:
    build:
      context: .
      dockerfile: publisher/Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - videos-data:/app/data/videos
      - ./publisher:/app/publisher
    restart: on-failure

volumes:
  videos-data:
    driver: local
