services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      PYTHONUNBUFFERED: "1"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --save 60 1000
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  script-generator:
    build:
      context: .
      dockerfile: scripts-generator/Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  video-creator:
    build:
      context: .
      dockerfile: video-creator/Dockerfile
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - videos-data:/app/data/videos
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rabbitreels
      POSTGRES_USER: rabbitreels
      POSTGRES_PASSWORD: rabbitreels_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rabbitreels -d rabbitreels"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      REDIS_URL: "redis://redis:6379/0"
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      FRONTEND_URL: "http://localhost:3001"
      DATABASE_URL: "postgresql://rabbitreels:rabbitreels_password@postgres:5432/rabbitreels"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - videos-data:/app/data/videos
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3001:80"
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:8080
    depends_on:
      - api
    restart: unless-stopped

volumes:
  videos-data:
    driver: local
  redis-data:
    driver: local
  postgres-data:
    driver: local
